[package]
edition = "2021"
name = "triangle"
version = "0.0.0"

[features]
generic = []

[dependencies]
itertools = "0.12.1"

[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["std"]
